package lineup;
public interface Enums
{
   enum agent {SOVA, VIPER, BRIMSTONE, KILLJOY, SAGE, CYPHER, PHOENIX, YORU, RAZE}
   enum map {ASCENT, BIND, HAVEN, ICEBOX, SPLIT}
   enum side {ATTACK, DEFEND}
   enum site {A, B, C, MID, GARAGE}
   enum projectile {MOLLY, SHOCK_DART, RECON_DART, SMOKE, SLOW, TELEPORT, GRENADE}
   enum throwType {JUMP_THROW, THROW, 
      TAP_NO_BOUNCE, TAP_ONE_BOUNCE, TAP_TWO_BOUNCE, 
      ONE_NO_BOUNCE, ONE_ONE_BOUNCE, ONE_TWO_BOUNCE, 
      TWO_NO_BOUNCE, TWO_ONE_BOUNCE, TWO_TWO_BOUNCE, 
      FULL_NO_BOUNCE, FULL_ONE_BOUNCE, FULL_TWO_BOUNCE, 
      TAP_NO_BOUNCE_JUMP, ONE_NO_BOUNCE_JUMP}
   enum land {DEFAULT, SECOND_DEFAULT, BACK_SITE, HEAVEN, SHORT, LONG, GREEN_BOX} //TODO 
}
